pipelines = {}
pipelines[#pipelines + 1] = {
    { dest="monitor_a", shader="shaders/pass.glsl", inputs={ img0="ObjID:2:assets/animals/free/underwater/Pexels Videos 2558530.mp4-SHRINK-REV.mp4", }},
    { dest="monitor_b", shader="shaders/pass.glsl", inputs={ img0="ObjID:3:assets/animals/free/underwater/Video (1).mp4-SHRINK-REV.mp4", }},
    { dest="monitor_c", shader="shaders/pass.glsl", inputs={ img0="0", }},
    { dest="monitor_d", shader="shaders/pass.glsl", inputs={ img0="0", }},
    { dest="monitor_d", shader="shaders/rotate.glsl", inputs={ img0="monitor_b", speed="monitor_c", }},
    { dest="monitor_b", shader="shaders/mask.glsl", inputs={ img0="monitor_c", mix="monitor_c", mask="monitor_b", }},
    { dest="monitor_c", shader="shaders/daily/00003.glsl", inputs={ img0="monitor_a", mix="monitor_c", time="monitor_a", }},
    { dest="monitor_a", shader="shaders/zoom.glsl", inputs={ img0="monitor_d", amount="monitor_d", }},
    { dest="monitor_a", shader="shaders/daily/00005.glsl", inputs={ img0="monitor_c", mix="monitor_b", time="monitor_b", }},
    { dest="monitor_c", shader="shaders/band_mix.glsl", inputs={ b="monitor_b", bands="monitor_c", mix="monitor_c", reference="monitor_b", time="monitor_a", a="monitor_b", }},
    { dest="monitor_c", shader="shaders/hsv_to_rgb.glsl", inputs={ hsv="monitor_b", }},
    { dest="monitor_c", shader="shaders/flip-vertical.glsl", inputs={ img0="monitor_c", mix="monitor_b", }},
    { dest="monitor_b", shader="shaders/rgb_to_hsv.glsl", inputs={ rgb="monitor_a", }},
    { dest="monitor_a", shader="shaders/displace_rgb.glsl", inputs={ img0="monitor_d", mix="monitor_c", }},
    { dest="monitor_d", shader="shaders/negate.glsl", inputs={ img0="monitor_c", }},
    { dest="monitor_a", shader="shaders/boxin.glsl", inputs={ img0="monitor_b", shrink="monitor_d", }},
    { dest="monitor_b", shader="shaders/invert.glsl", inputs={ img0="monitor_c", mix="monitor_a", }},
    { dest="monitor_d", shader="shaders/feedback/blackbar-exploder.glsl", inputs={ last_out="monitor_b", img0="monitor_b", vertical="monitor_c", }},
    { dest="monitor_d", shader="shaders/band.glsl", inputs={ img0="monitor_b", mix="monitor_d", bands="monitor_c", target="monitor_a", }},
    { dest="monitor_c", shader="shaders/text-surround.glsl", inputs={ text0="monitor_c", img0="monitor_b", speed="monitor_b", }},
    { dest="monitor_c", shader="shaders/magnitude.glsl", inputs={ img0="monitor_c", }},
    { dest="monitor_b", shader="shaders/filter-whites.glsl", inputs={ img0="monitor_b", thresh="monitor_c", }},
    { dest="monitor_c", shader="shaders/feedback/explode.glsl", inputs={ last_out="monitor_a", }},
    { dest="monitor_c", shader="shaders/color_01.glsl", inputs={ img0="monitor_d", mix="monitor_a", }},
    { dest="monitor_c", shader="shaders/color-tweak.glsl", inputs={ gamma="monitor_d", contrast_dec="monitor_a", gamma_inc="monitor_d", brightness="monitor_c", split="monitor_d", contrast="monitor_b", img0="monitor_b", contrast_inc="monitor_b", gamma_dec="monitor_c", }},
    { dest="monitor_a", shader="shaders/daily/00002.glsl", inputs={ img0="monitor_c", mix="monitor_d", contrast="monitor_b", }},
    { dest="monitor_b", shader="shaders/masks/stripes.glsl", inputs={ width="monitor_c", height="monitor_a", }},
    { dest="monitor_b", shader="shaders/negative.glsl", inputs={ img0="monitor_d", mix="monitor_d", }},
    { dest="monitor_d", shader="shaders/explode.glsl", inputs={ img0="monitor_a", mix="monitor_c", }},
    { dest="monitor_c", shader="shaders/blur.glsl", inputs={ img0="monitor_c", mix="monitor_b", }},
    { dest="monitor_d", shader="shaders/displace_by_rgb.glsl", inputs={ img0="monitor_b", mix="monitor_d", }},
    { dest="monitor_a", shader="shaders/displace_by_lum.glsl", inputs={ img0="monitor_d", mix="monitor_b", }},
    { dest="monitor_c", shader="shaders/pass.glsl", inputs={ img0="monitor_a", }},
    { dest="monitor_d", shader="shaders/brighter.glsl", inputs={ img0="monitor_c", intensity="monitor_c", }},
    { dest="monitor_b", shader="shaders/white-to-black.glsl", inputs={ img0="monitor_a", }},
    { dest="monitor_c", shader="shaders/maskify.glsl", inputs={ img0="monitor_a", lumin_threshold="monitor_a", negate="monitor_d", }},
    { dest="monitor_a", shader="shaders/edges.glsl", inputs={ noise="monitor_c", img0="monitor_a", thresh="monitor_c", negate="monitor_b", mix="monitor_b", }},
    { dest="monitor_b", shader="shaders/video-wall.glsl", inputs={ img0="monitor_b", mix="monitor_a", boxes="monitor_d", min_brightness="monitor_d", }},
    { dest="monitor_a", shader="shaders/flowing_noise.glsl", inputs={ time="monitor_d", }},
    { dest="monitor_a", shader="shaders/lums.glsl", inputs={ img0="monitor_b", }},
    { dest="monitor_b", shader="shaders/test.glsl", inputs={ img0="monitor_b", blue="monitor_a", }},
    { dest="monitor_d", shader="shaders/flip.glsl", inputs={ img0="monitor_b", mix="monitor_d", }},
    { dest="monitor_d", shader="shaders/knoty.glsl", inputs={ img0="monitor_b", mix="monitor_d", }},
    { dest="monitor_d", shader="shaders/masks/spiral.glsl", inputs={ balance="monitor_a", speed="monitor_a", }},
    { dest="monitor_b", shader="shaders/kscope.glsl", inputs={ img0="monitor_a", center="monitor_a", tweak_1="monitor_a", mix="monitor_c", }},
    { dest="monitor_b", shader="shaders/delay.glsl", inputs={ img0="monitor_c", mix="monitor_a", }},
    { dest="monitor_d", shader="shaders/color_02.glsl", inputs={ img0="monitor_a", mix="monitor_d", }},
    { dest="monitor_d", shader="shaders/mix_fade.glsl", inputs={ b="monitor_a", mix="monitor_b", a="monitor_b", }},
    { dest="monitor_d", shader="shaders/rotate-corners.glsl", inputs={ img0="monitor_a", }},
    { dest="monitor_b", shader="shaders/daily/00006.glsl", inputs={ b="monitor_d", mix="monitor_c", a="monitor_a", }},
    { dest="monitor_a", shader="shaders/feedback/implode.glsl", inputs={ last_out="monitor_b", }},
    { dest="monitor_c", shader="shaders/move.glsl", inputs={ img0="monitor_a", offset_y="monitor_d", offset_x="monitor_b", }},
    { dest="monitor_d", shader="shaders/fake-3d.glsl", inputs={ img0="monitor_b", scale="monitor_d", depth="monitor_d", }},
    { dest="monitor_b", shader="shaders/pixelate.glsl", inputs={ img0="monitor_b", mix="monitor_c", }},
    { dest="monitor_b", shader="shaders/rgb.glsl", inputs={ red="monitor_b", green="monitor_d", blue="monitor_a", }},
    { dest="monitor_d", shader="shaders/rainbow-band.glsl", inputs={ img0="monitor_d", mix="monitor_d", time="monitor_a", }},
    { dest="monitor_b", shader="shaders/mix.glsl", inputs={ b="monitor_a", mix_diff="monitor_a", mix_fade="monitor_b", mix_fade3="monitor_c", mix_fade2="monitor_a", mix_bars="monitor_b", mix_lumin_b="monitor_c", mix_lumin_a="monitor_a", a="monitor_b", }},
    { dest="monitor_d", shader="shaders/pass.glsl", inputs={ img0="monitor_d", }},
}

pipelines[#pipelines + 1] = {
    { dest="monitor_a", shader="shaders/pass.glsl", inputs={ img0="ObjID:2:assets/animals/free/underwater/Pexels Videos 2558530.mp4-SHRINK-REV.mp4", }},
    { dest="monitor_b", shader="shaders/pass.glsl", inputs={ img0="ObjID:3:assets/animals/free/underwater/Video (1).mp4-SHRINK-REV.mp4", }},
    { dest="monitor_c", shader="shaders/pass.glsl", inputs={ img0="0", }},
    { dest="monitor_d", shader="shaders/pass.glsl", inputs={ img0="0", }},
    { dest="monitor_c", shader="shaders/color-tweak.glsl", inputs={ gamma_dec="monitor_c", gamma="monitor_c", split="monitor_c", img0="monitor_a", brightness="monitor_a", contrast_dec="monitor_b", gamma_inc="monitor_b", contrast_inc="monitor_a", contrast="monitor_c", }},
    { dest="monitor_a", shader="shaders/flip-vertical.glsl", inputs={ img0="monitor_d", mix="monitor_b", }},
    { dest="monitor_d", shader="shaders/feedback/blackbar-exploder.glsl", inputs={ last_out="monitor_c", img0="monitor_a", vertical="monitor_d", }},
    { dest="monitor_d", shader="shaders/displace_by_lum.glsl", inputs={ img0="monitor_a", mix="monitor_b", }},
    { dest="monitor_b", shader="shaders/daily/00006.glsl", inputs={ b="monitor_c", a="monitor_b", mix="monitor_b", }},
    { dest="monitor_b", shader="shaders/rotate-corners.glsl", inputs={ img0="monitor_b", }},
    { dest="monitor_b", shader="shaders/rotate.glsl", inputs={ img0="monitor_a", speed="monitor_d", }},
    { dest="monitor_b", shader="shaders/invert.glsl", inputs={ mix="monitor_b", img0="monitor_a", }},
    { dest="monitor_b", shader="shaders/masks/stripes.glsl", inputs={ height="monitor_d", width="monitor_a", }},
    { dest="monitor_d", shader="shaders/magnitude.glsl", inputs={ img0="monitor_a", }},
    { dest="monitor_c", shader="shaders/test.glsl", inputs={ img0="monitor_c", blue="monitor_d", }},
    { dest="monitor_a", shader="shaders/fake-3d.glsl", inputs={ scale="monitor_c", img0="monitor_a", depth="monitor_c", }},
    { dest="monitor_a", shader="shaders/mix.glsl", inputs={ mix_diff="monitor_b", mix_fade2="monitor_b", mix_fade3="monitor_b", a="monitor_d", mix_fade="monitor_b", mix_lumin_b="monitor_c", b="monitor_c", mix_lumin_a="monitor_d", mix_bars="monitor_c", }},
    { dest="monitor_c", shader="shaders/daily/00002.glsl", inputs={ mix="monitor_a", img0="monitor_a", contrast="monitor_b", }},
    { dest="monitor_b", shader="shaders/feedback/explode.glsl", inputs={ last_out="monitor_c", }},
    { dest="monitor_b", shader="shaders/brighter.glsl", inputs={ img0="monitor_c", intensity="monitor_b", }},
    { dest="monitor_d", shader="shaders/rainbow-band.glsl", inputs={ mix="monitor_d", img0="monitor_a", time="monitor_c", }},
    { dest="monitor_d", shader="shaders/band.glsl", inputs={ target="monitor_d", bands="monitor_a", img0="monitor_a", mix="monitor_b", }},
    { dest="monitor_d", shader="shaders/band_mix.glsl", inputs={ a="monitor_c", time="monitor_d", bands="monitor_a", b="monitor_b", mix="monitor_c", reference="monitor_c", }},
    { dest="monitor_a", shader="shaders/color_02.glsl", inputs={ img0="monitor_a", mix="monitor_b", }},
    { dest="monitor_b", shader="shaders/boxin.glsl", inputs={ img0="monitor_d", shrink="monitor_d", }},
    { dest="monitor_c", shader="shaders/edges.glsl", inputs={ noise="monitor_b", negate="monitor_a", img0="monitor_d", mix="monitor_c", thresh="monitor_a", }},
    { dest="monitor_a", shader="shaders/zoom.glsl", inputs={ img0="monitor_b", amount="monitor_a", }},
    { dest="monitor_c", shader="shaders/knoty.glsl", inputs={ img0="monitor_a", mix="monitor_a", }},
    { dest="monitor_b", shader="shaders/lums.glsl", inputs={ img0="monitor_d", }},
    { dest="monitor_a", shader="shaders/video-wall.glsl", inputs={ min_brightness="monitor_c", boxes="monitor_a", img0="monitor_d", mix="monitor_b", }},
    { dest="monitor_b", shader="shaders/displace_rgb.glsl", inputs={ img0="monitor_d", mix="monitor_d", }},
    { dest="monitor_c", shader="shaders/maskify.glsl", inputs={ negate="monitor_c", img0="monitor_a", lumin_threshold="monitor_b", }},
    { dest="monitor_b", shader="shaders/mix_fade.glsl", inputs={ b="monitor_c", a="monitor_d", mix="monitor_c", }},
    { dest="monitor_b", shader="shaders/pass.glsl", inputs={ img0="monitor_a", }},
    { dest="monitor_a", shader="shaders/delay.glsl", inputs={ img0="monitor_a", mix="monitor_a", }},
    { dest="monitor_c", shader="shaders/negative.glsl", inputs={ img0="monitor_c", mix="monitor_b", }},
    { dest="monitor_d", shader="shaders/hsv_to_rgb.glsl", inputs={ hsv="monitor_d", }},
    { dest="monitor_b", shader="shaders/kscope.glsl", inputs={ mix="monitor_c", center="monitor_a", img0="monitor_c", tweak_1="monitor_c", }},
    { dest="monitor_d", shader="shaders/daily/00003.glsl", inputs={ mix="monitor_a", img0="monitor_a", time="monitor_c", }},
    { dest="monitor_d", shader="shaders/flowing_noise.glsl", inputs={ time="monitor_a", }},
    { dest="monitor_b", shader="shaders/pixelate.glsl", inputs={ img0="monitor_a", mix="monitor_a", }},
    { dest="monitor_a", shader="shaders/rgb.glsl", inputs={ red="monitor_c", green="monitor_c", blue="monitor_a", }},
    { dest="monitor_c", shader="shaders/flip.glsl", inputs={ img0="monitor_a", mix="monitor_c", }},
    { dest="monitor_c", shader="shaders/move.glsl", inputs={ offset_x="monitor_b", img0="monitor_d", offset_y="monitor_a", }},
    { dest="monitor_d", shader="shaders/daily/00005.glsl", inputs={ mix="monitor_a", img0="monitor_a", time="monitor_a", }},
    { dest="monitor_c", shader="shaders/masks/spiral.glsl", inputs={ balance="monitor_a", speed="monitor_d", }},
    { dest="monitor_c", shader="shaders/blur.glsl", inputs={ img0="monitor_b", mix="monitor_d", }},
    { dest="monitor_b", shader="shaders/feedback/implode.glsl", inputs={ last_out="monitor_d", }},
    { dest="monitor_b", shader="shaders/filter-whites.glsl", inputs={ img0="monitor_b", thresh="monitor_a", }},
    { dest="monitor_d", shader="shaders/negate.glsl", inputs={ img0="monitor_a", }},
    { dest="monitor_d", shader="shaders/rgb_to_hsv.glsl", inputs={ rgb="monitor_c", }},
    { dest="monitor_b", shader="shaders/displace_by_rgb.glsl", inputs={ img0="monitor_a", mix="monitor_d", }},
    { dest="monitor_c", shader="shaders/color_01.glsl", inputs={ img0="monitor_c", mix="monitor_c", }},
    { dest="monitor_d", shader="shaders/explode.glsl", inputs={ img0="monitor_a", mix="monitor_d", }},
    { dest="monitor_b", shader="shaders/mask.glsl", inputs={ mask="monitor_b", img0="monitor_a", mix="monitor_c", }},
    { dest="monitor_d", shader="shaders/text-surround.glsl", inputs={ speed="monitor_c", text0="monitor_d", img0="monitor_b", }},
    { dest="monitor_b", shader="shaders/white-to-black.glsl", inputs={ img0="monitor_b", }},
    { dest="monitor_c", shader="shaders/pass.glsl", inputs={ img0="monitor_c", }},
}

pipelines[#pipelines + 1] = {
    { dest="monitor_a", shader="shaders/pass.glsl", inputs={ img0="ObjID:2:assets/animals/free/underwater/Pexels Videos 2558530.mp4-SHRINK-REV.mp4", }},
    { dest="monitor_b", shader="shaders/pass.glsl", inputs={ img0="ObjID:3:assets/animals/free/underwater/Video (1).mp4-SHRINK-REV.mp4", }},
    { dest="monitor_c", shader="shaders/pass.glsl", inputs={ img0="0", }},
    { dest="monitor_d", shader="shaders/pass.glsl", inputs={ img0="0", }},
    { dest="monitor_c", shader="shaders/white-to-black.glsl", inputs={ img0="monitor_c", }},
    { dest="monitor_a", shader="shaders/invert.glsl", inputs={ mix="monitor_d", img0="monitor_c", }},
    { dest="monitor_b", shader="shaders/rotate.glsl", inputs={ img0="monitor_d", speed="monitor_d", }},
    { dest="monitor_c", shader="shaders/boxin.glsl", inputs={ img0="monitor_a", shrink="monitor_d", }},
    { dest="monitor_d", shader="shaders/flip.glsl", inputs={ img0="monitor_d", mix="monitor_d", }},
    { dest="monitor_b", shader="shaders/text-surround.glsl", inputs={ speed="monitor_b", text0="monitor_a", img0="monitor_b", }},
    { dest="monitor_a", shader="shaders/pixelate.glsl", inputs={ img0="monitor_c", mix="monitor_c", }},
    { dest="monitor_d", shader="shaders/maskify.glsl", inputs={ negate="monitor_d", img0="monitor_c", lumin_threshold="monitor_d", }},
    { dest="monitor_c", shader="shaders/daily/00005.glsl", inputs={ mix="monitor_b", img0="monitor_d", time="monitor_b", }},
    { dest="monitor_c", shader="shaders/rgb_to_hsv.glsl", inputs={ rgb="monitor_a", }},
    { dest="monitor_c", shader="shaders/blur.glsl", inputs={ img0="monitor_b", mix="monitor_a", }},
    { dest="monitor_b", shader="shaders/zoom.glsl", inputs={ img0="monitor_a", amount="monitor_d", }},
    { dest="monitor_a", shader="shaders/filter-whites.glsl", inputs={ img0="monitor_c", thresh="monitor_c", }},
    { dest="monitor_c", shader="shaders/daily/00006.glsl", inputs={ b="monitor_d", a="monitor_d", mix="monitor_b", }},
    { dest="monitor_b", shader="shaders/rgb.glsl", inputs={ red="monitor_d", green="monitor_d", blue="monitor_c", }},
    { dest="monitor_c", shader="shaders/kscope.glsl", inputs={ mix="monitor_b", center="monitor_b", img0="monitor_a", tweak_1="monitor_d", }},
    { dest="monitor_c", shader="shaders/color_02.glsl", inputs={ img0="monitor_a", mix="monitor_a", }},
    { dest="monitor_c", shader="shaders/pass.glsl", inputs={ img0="monitor_a", }},
    { dest="monitor_b", shader="shaders/negate.glsl", inputs={ img0="monitor_a", }},
    { dest="monitor_a", shader="shaders/video-wall.glsl", inputs={ min_brightness="monitor_a", boxes="monitor_c", img0="monitor_c", mix="monitor_c", }},
    { dest="monitor_b", shader="shaders/flip-vertical.glsl", inputs={ img0="monitor_b", mix="monitor_c", }},
    { dest="monitor_c", shader="shaders/feedback/blackbar-exploder.glsl", inputs={ last_out="monitor_a", img0="monitor_d", vertical="monitor_b", }},
    { dest="monitor_d", shader="shaders/mix.glsl", inputs={ mix_diff="monitor_c", mix_fade2="monitor_d", mix_fade3="monitor_b", a="monitor_d", mix_fade="monitor_b", mix_lumin_b="monitor_b", b="monitor_c", mix_lumin_a="monitor_d", mix_bars="monitor_c", }},
    { dest="monitor_b", shader="shaders/fake-3d.glsl", inputs={ scale="monitor_d", img0="monitor_b", depth="monitor_b", }},
    { dest="monitor_c", shader="shaders/hsv_to_rgb.glsl", inputs={ hsv="monitor_a", }},
    { dest="monitor_d", shader="shaders/daily/00003.glsl", inputs={ mix="monitor_b", img0="monitor_c", time="monitor_b", }},
    { dest="monitor_d", shader="shaders/mask.glsl", inputs={ mask="monitor_c", img0="monitor_d", mix="monitor_d", }},
    { dest="monitor_d", shader="shaders/edges.glsl", inputs={ noise="monitor_a", negate="monitor_d", img0="monitor_a", mix="monitor_d", thresh="monitor_b", }},
    { dest="monitor_a", shader="shaders/test.glsl", inputs={ img0="monitor_b", blue="monitor_d", }},
    { dest="monitor_c", shader="shaders/daily/00002.glsl", inputs={ mix="monitor_b", img0="monitor_b", contrast="monitor_d", }},
    { dest="monitor_d", shader="shaders/band_mix.glsl", inputs={ a="monitor_d", time="monitor_c", bands="monitor_d", b="monitor_d", mix="monitor_d", reference="monitor_a", }},
    { dest="monitor_d", shader="shaders/feedback/implode.glsl", inputs={ last_out="monitor_c", }},
    { dest="monitor_d", shader="shaders/move.glsl", inputs={ offset_x="monitor_b", img0="monitor_a", offset_y="monitor_b", }},
    { dest="monitor_a", shader="shaders/explode.glsl", inputs={ img0="monitor_d", mix="monitor_a", }},
    { dest="monitor_a", shader="shaders/displace_by_lum.glsl", inputs={ img0="monitor_d", mix="monitor_a", }},
    { dest="monitor_d", shader="shaders/delay.glsl", inputs={ img0="monitor_a", mix="monitor_d", }},
    { dest="monitor_c", shader="shaders/color-tweak.glsl", inputs={ gamma_dec="monitor_d", gamma="monitor_a", split="monitor_d", img0="monitor_b", brightness="monitor_d", contrast_dec="monitor_a", gamma_inc="monitor_a", contrast_inc="monitor_c", contrast="monitor_d", }},
    { dest="monitor_b", shader="shaders/magnitude.glsl", inputs={ img0="monitor_c", }},
    { dest="monitor_b", shader="shaders/lums.glsl", inputs={ img0="monitor_d", }},
    { dest="monitor_c", shader="shaders/masks/stripes.glsl", inputs={ height="monitor_b", width="monitor_d", }},
    { dest="monitor_b", shader="shaders/flowing_noise.glsl", inputs={ time="monitor_b", }},
    { dest="monitor_d", shader="shaders/masks/spiral.glsl", inputs={ balance="monitor_b", speed="monitor_c", }},
    { dest="monitor_a", shader="shaders/mix_fade.glsl", inputs={ b="monitor_c", a="monitor_c", mix="monitor_d", }},
    { dest="monitor_b", shader="shaders/displace_by_rgb.glsl", inputs={ img0="monitor_a", mix="monitor_a", }},
    { dest="monitor_a", shader="shaders/brighter.glsl", inputs={ img0="monitor_b", intensity="monitor_b", }},
    { dest="monitor_c", shader="shaders/negative.glsl", inputs={ img0="monitor_c", mix="monitor_b", }},
    { dest="monitor_c", shader="shaders/knoty.glsl", inputs={ img0="monitor_c", mix="monitor_d", }},
    { dest="monitor_b", shader="shaders/rotate-corners.glsl", inputs={ img0="monitor_d", }},
    { dest="monitor_c", shader="shaders/rainbow-band.glsl", inputs={ mix="monitor_c", img0="monitor_a", time="monitor_b", }},
    { dest="monitor_b", shader="shaders/band.glsl", inputs={ target="monitor_a", bands="monitor_c", img0="monitor_c", mix="monitor_b", }},
    { dest="monitor_b", shader="shaders/color_01.glsl", inputs={ img0="monitor_a", mix="monitor_a", }},
    { dest="monitor_a", shader="shaders/feedback/explode.glsl", inputs={ last_out="monitor_d", }},
    { dest="monitor_c", shader="shaders/displace_rgb.glsl", inputs={ img0="monitor_b", mix="monitor_d", }},
    { dest="monitor_a", shader="shaders/pass.glsl", inputs={ img0="monitor_a", }},
}

pipelines[#pipelines + 1] = {
    { dest="monitor_a", shader="shaders/pass.glsl", inputs={ img0="ObjID:2:assets/animals/free/underwater/Pexels Videos 2558530.mp4-SHRINK-REV.mp4", }},
    { dest="monitor_b", shader="shaders/pass.glsl", inputs={ img0="ObjID:3:assets/animals/free/underwater/Video (1).mp4-SHRINK-REV.mp4", }},
    { dest="monitor_c", shader="shaders/pass.glsl", inputs={ img0="0", }},
    { dest="monitor_d", shader="shaders/pass.glsl", inputs={ img0="0", }},
    { dest="monitor_b", shader="shaders/displace_by_lum.glsl", inputs={ img0="monitor_d", mix="monitor_a", }},
    { dest="monitor_a", shader="shaders/magnitude.glsl", inputs={ img0="monitor_a", }},
    { dest="monitor_b", shader="shaders/filter-whites.glsl", inputs={ img0="monitor_c", thresh="monitor_d", }},
    { dest="monitor_a", shader="shaders/video-wall.glsl", inputs={ min_brightness="monitor_c", boxes="monitor_a", img0="monitor_c", mix="monitor_c", }},
    { dest="monitor_d", shader="shaders/band.glsl", inputs={ target="monitor_a", bands="monitor_d", img0="monitor_d", mix="monitor_d", }},
    { dest="monitor_a", shader="shaders/kscope.glsl", inputs={ mix="monitor_a", center="monitor_c", img0="monitor_b", tweak_1="monitor_c", }},
    { dest="monitor_c", shader="shaders/mix_fade.glsl", inputs={ b="monitor_c", a="monitor_a", mix="monitor_c", }},
    { dest="monitor_d", shader="shaders/fake-3d.glsl", inputs={ scale="monitor_b", img0="monitor_a", depth="monitor_a", }},
    { dest="monitor_c", shader="shaders/negate.glsl", inputs={ img0="monitor_d", }},
    { dest="monitor_b", shader="shaders/feedback/explode.glsl", inputs={ last_out="monitor_d", }},
    { dest="monitor_b", shader="shaders/daily/00003.glsl", inputs={ mix="monitor_d", img0="monitor_b", time="monitor_a", }},
    { dest="monitor_b", shader="shaders/masks/stripes.glsl", inputs={ height="monitor_c", width="monitor_b", }},
    { dest="monitor_d", shader="shaders/daily/00002.glsl", inputs={ mix="monitor_b", img0="monitor_a", contrast="monitor_a", }},
    { dest="monitor_a", shader="shaders/mix.glsl", inputs={ mix_diff="monitor_d", mix_fade2="monitor_d", mix_fade3="monitor_d", a="monitor_d", mix_fade="monitor_c", mix_lumin_b="monitor_d", b="monitor_c", mix_lumin_a="monitor_b", mix_bars="monitor_b", }},
    { dest="monitor_d", shader="shaders/flip-vertical.glsl", inputs={ img0="monitor_c", mix="monitor_c", }},
    { dest="monitor_a", shader="shaders/color_01.glsl", inputs={ img0="monitor_a", mix="monitor_a", }},
    { dest="monitor_d", shader="shaders/test.glsl", inputs={ img0="monitor_b", blue="monitor_a", }},
    { dest="monitor_c", shader="shaders/blur.glsl", inputs={ img0="monitor_b", mix="monitor_c", }},
    { dest="monitor_c", shader="shaders/explode.glsl", inputs={ img0="monitor_c", mix="monitor_c", }},
    { dest="monitor_a", shader="shaders/daily/00005.glsl", inputs={ mix="monitor_a", img0="monitor_b", time="monitor_d", }},
    { dest="monitor_d", shader="shaders/flowing_noise.glsl", inputs={ time="monitor_d", }},
    { dest="monitor_c", shader="shaders/delay.glsl", inputs={ img0="monitor_d", mix="monitor_b", }},
    { dest="monitor_d", shader="shaders/daily/00006.glsl", inputs={ b="monitor_a", a="monitor_b", mix="monitor_b", }},
    { dest="monitor_c", shader="shaders/edges.glsl", inputs={ noise="monitor_c", negate="monitor_d", img0="monitor_b", mix="monitor_a", thresh="monitor_b", }},
    { dest="monitor_c", shader="shaders/feedback/blackbar-exploder.glsl", inputs={ last_out="monitor_b", img0="monitor_d", vertical="monitor_b", }},
    { dest="monitor_c", shader="shaders/color-tweak.glsl", inputs={ gamma_dec="monitor_b", gamma="monitor_a", split="monitor_a", img0="monitor_d", brightness="monitor_a", contrast_dec="monitor_c", gamma_inc="monitor_a", contrast_inc="monitor_d", contrast="monitor_b", }},
    { dest="monitor_d", shader="shaders/text-surround.glsl", inputs={ speed="monitor_b", text0="monitor_b", img0="monitor_c", }},
    { dest="monitor_c", shader="shaders/displace_rgb.glsl", inputs={ img0="monitor_b", mix="monitor_b", }},
    { dest="monitor_d", shader="shaders/mask.glsl", inputs={ mask="monitor_c", img0="monitor_a", mix="monitor_d", }},
    { dest="monitor_c", shader="shaders/rainbow-band.glsl", inputs={ mix="monitor_d", img0="monitor_b", time="monitor_a", }},
    { dest="monitor_a", shader="shaders/zoom.glsl", inputs={ img0="monitor_a", amount="monitor_b", }},
    { dest="monitor_a", shader="shaders/invert.glsl", inputs={ mix="monitor_a", img0="monitor_a", }},
    { dest="monitor_d", shader="shaders/lums.glsl", inputs={ img0="monitor_a", }},
    { dest="monitor_b", shader="shaders/rotate-corners.glsl", inputs={ img0="monitor_b", }},
    { dest="monitor_a", shader="shaders/white-to-black.glsl", inputs={ img0="monitor_b", }},
    { dest="monitor_a", shader="shaders/displace_by_rgb.glsl", inputs={ img0="monitor_a", mix="monitor_b", }},
    { dest="monitor_d", shader="shaders/masks/spiral.glsl", inputs={ balance="monitor_d", speed="monitor_a", }},
    { dest="monitor_d", shader="shaders/rgb.glsl", inputs={ red="monitor_d", green="monitor_a", blue="monitor_b", }},
    { dest="monitor_b", shader="shaders/brighter.glsl", inputs={ img0="monitor_d", intensity="monitor_b", }},
    { dest="monitor_d", shader="shaders/color_02.glsl", inputs={ img0="monitor_a", mix="monitor_a", }},
    { dest="monitor_d", shader="shaders/move.glsl", inputs={ offset_x="monitor_c", img0="monitor_a", offset_y="monitor_a", }},
    { dest="monitor_a", shader="shaders/maskify.glsl", inputs={ negate="monitor_a", img0="monitor_b", lumin_threshold="monitor_d", }},
    { dest="monitor_c", shader="shaders/rotate.glsl", inputs={ img0="monitor_c", speed="monitor_c", }},
    { dest="monitor_c", shader="shaders/flip.glsl", inputs={ img0="monitor_c", mix="monitor_c", }},
    { dest="monitor_d", shader="shaders/band_mix.glsl", inputs={ a="monitor_a", time="monitor_b", bands="monitor_c", b="monitor_d", mix="monitor_b", reference="monitor_a", }},
    { dest="monitor_a", shader="shaders/hsv_to_rgb.glsl", inputs={ hsv="monitor_c", }},
    { dest="monitor_d", shader="shaders/rgb_to_hsv.glsl", inputs={ rgb="monitor_d", }},
    { dest="monitor_d", shader="shaders/boxin.glsl", inputs={ img0="monitor_d", shrink="monitor_d", }},
    { dest="monitor_c", shader="shaders/feedback/implode.glsl", inputs={ last_out="monitor_a", }},
    { dest="monitor_a", shader="shaders/pass.glsl", inputs={ img0="monitor_b", }},
    { dest="monitor_c", shader="shaders/pixelate.glsl", inputs={ img0="monitor_d", mix="monitor_d", }},
    { dest="monitor_b", shader="shaders/knoty.glsl", inputs={ img0="monitor_b", mix="monitor_b", }},
    { dest="monitor_a", shader="shaders/negative.glsl", inputs={ img0="monitor_d", mix="monitor_a", }},
    { dest="monitor_b", shader="shaders/pass.glsl", inputs={ img0="monitor_b", }},
}

pipelines[#pipelines + 1] = {
    { dest="monitor_a", shader="shaders/pass.glsl", inputs={ img0="ObjID:2:assets/animals/free/underwater/Pexels Videos 2558530.mp4-SHRINK-REV.mp4", }},
    { dest="monitor_b", shader="shaders/pass.glsl", inputs={ img0="ObjID:3:assets/animals/free/underwater/Video (1).mp4-SHRINK-REV.mp4", }},
    { dest="monitor_c", shader="shaders/pass.glsl", inputs={ img0="0", }},
    { dest="monitor_d", shader="shaders/pass.glsl", inputs={ img0="0", }},
    { dest="monitor_b", shader="shaders/feedback/explode.glsl", inputs={ last_out="monitor_d", }},
    { dest="monitor_b", shader="shaders/magnitude.glsl", inputs={ img0="monitor_c", }},
    { dest="monitor_c", shader="shaders/daily/00003.glsl", inputs={ mix="monitor_c", img0="monitor_a", time="monitor_c", }},
    { dest="monitor_c", shader="shaders/color_01.glsl", inputs={ img0="monitor_d", mix="monitor_b", }},
    { dest="monitor_d", shader="shaders/daily/00005.glsl", inputs={ mix="monitor_d", img0="monitor_a", time="monitor_c", }},
    { dest="monitor_d", shader="shaders/knoty.glsl", inputs={ img0="monitor_a", mix="monitor_a", }},
    { dest="monitor_d", shader="shaders/rainbow-band.glsl", inputs={ mix="monitor_c", img0="monitor_b", time="monitor_a", }},
    { dest="monitor_c", shader="shaders/explode.glsl", inputs={ img0="monitor_b", mix="monitor_c", }},
    { dest="monitor_d", shader="shaders/video-wall.glsl", inputs={ min_brightness="monitor_c", boxes="monitor_a", img0="monitor_d", mix="monitor_b", }},
    { dest="monitor_d", shader="shaders/hsv_to_rgb.glsl", inputs={ hsv="monitor_b", }},
    { dest="monitor_d", shader="shaders/delay.glsl", inputs={ img0="monitor_a", mix="monitor_c", }},
    { dest="monitor_a", shader="shaders/maskify.glsl", inputs={ negate="monitor_b", img0="monitor_b", lumin_threshold="monitor_a", }},
    { dest="monitor_b", shader="shaders/test.glsl", inputs={ img0="monitor_b", blue="monitor_c", }},
    { dest="monitor_c", shader="shaders/daily/00006.glsl", inputs={ b="monitor_b", a="monitor_a", mix="monitor_a", }},
    { dest="monitor_a", shader="shaders/band_mix.glsl", inputs={ a="monitor_d", time="monitor_b", bands="monitor_a", b="monitor_a", mix="monitor_d", reference="monitor_d", }},
    { dest="monitor_b", shader="shaders/fake-3d.glsl", inputs={ scale="monitor_a", img0="monitor_b", depth="monitor_d", }},
    { dest="monitor_a", shader="shaders/kscope.glsl", inputs={ mix="monitor_b", center="monitor_a", img0="monitor_a", tweak_1="monitor_b", }},
    { dest="monitor_c", shader="shaders/edges.glsl", inputs={ noise="monitor_c", negate="monitor_b", img0="monitor_c", mix="monitor_d", thresh="monitor_c", }},
    { dest="monitor_a", shader="shaders/feedback/implode.glsl", inputs={ last_out="monitor_a", }},
    { dest="monitor_d", shader="shaders/filter-whites.glsl", inputs={ img0="monitor_c", thresh="monitor_c", }},
    { dest="monitor_a", shader="shaders/flip-vertical.glsl", inputs={ img0="monitor_a", mix="monitor_c", }},
    { dest="monitor_a", shader="shaders/mix_fade.glsl", inputs={ b="monitor_a", a="monitor_c", mix="monitor_a", }},
    { dest="monitor_b", shader="shaders/daily/00002.glsl", inputs={ mix="monitor_c", img0="monitor_b", contrast="monitor_a", }},
    { dest="monitor_d", shader="shaders/color-tweak.glsl", inputs={ gamma_dec="monitor_b", gamma="monitor_d", split="monitor_c", img0="monitor_c", brightness="monitor_a", contrast_dec="monitor_d", gamma_inc="monitor_b", contrast_inc="monitor_d", contrast="monitor_c", }},
    { dest="monitor_a", shader="shaders/flip.glsl", inputs={ img0="monitor_a", mix="monitor_a", }},
    { dest="monitor_a", shader="shaders/brighter.glsl", inputs={ img0="monitor_a", intensity="monitor_b", }},
    { dest="monitor_d", shader="shaders/mix.glsl", inputs={ mix_diff="monitor_a", mix_fade2="monitor_c", mix_fade3="monitor_b", a="monitor_a", mix_fade="monitor_c", mix_lumin_b="monitor_d", b="monitor_c", mix_lumin_a="monitor_a", mix_bars="monitor_d", }},
    { dest="monitor_b", shader="shaders/rotate.glsl", inputs={ img0="monitor_a", speed="monitor_b", }},
    { dest="monitor_a", shader="shaders/band.glsl", inputs={ target="monitor_c", bands="monitor_d", img0="monitor_a", mix="monitor_d", }},
    { dest="monitor_d", shader="shaders/masks/stripes.glsl", inputs={ height="monitor_d", width="monitor_c", }},
    { dest="monitor_c", shader="shaders/blur.glsl", inputs={ img0="monitor_c", mix="monitor_d", }},
    { dest="monitor_c", shader="shaders/rotate-corners.glsl", inputs={ img0="monitor_a", }},
    { dest="monitor_c", shader="shaders/lums.glsl", inputs={ img0="monitor_a", }},
    { dest="monitor_d", shader="shaders/flowing_noise.glsl", inputs={ time="monitor_d", }},
    { dest="monitor_d", shader="shaders/pixelate.glsl", inputs={ img0="monitor_a", mix="monitor_d", }},
    { dest="monitor_c", shader="shaders/invert.glsl", inputs={ mix="monitor_a", img0="monitor_c", }},
    { dest="monitor_c", shader="shaders/zoom.glsl", inputs={ img0="monitor_c", amount="monitor_b", }},
    { dest="monitor_a", shader="shaders/feedback/blackbar-exploder.glsl", inputs={ last_out="monitor_a", img0="monitor_a", vertical="monitor_c", }},
    { dest="monitor_c", shader="shaders/rgb.glsl", inputs={ red="monitor_a", green="monitor_c", blue="monitor_d", }},
    { dest="monitor_a", shader="shaders/white-to-black.glsl", inputs={ img0="monitor_a", }},
    { dest="monitor_a", shader="shaders/negative.glsl", inputs={ img0="monitor_d", mix="monitor_b", }},
    { dest="monitor_c", shader="shaders/negate.glsl", inputs={ img0="monitor_a", }},
    { dest="monitor_d", shader="shaders/color_02.glsl", inputs={ img0="monitor_a", mix="monitor_c", }},
    { dest="monitor_d", shader="shaders/mask.glsl", inputs={ mask="monitor_c", img0="monitor_a", mix="monitor_d", }},
    { dest="monitor_d", shader="shaders/displace_by_lum.glsl", inputs={ img0="monitor_a", mix="monitor_b", }},
    { dest="monitor_b", shader="shaders/pass.glsl", inputs={ img0="monitor_d", }},
    { dest="monitor_d", shader="shaders/displace_rgb.glsl", inputs={ img0="monitor_b", mix="monitor_a", }},
    { dest="monitor_c", shader="shaders/displace_by_rgb.glsl", inputs={ img0="monitor_c", mix="monitor_a", }},
    { dest="monitor_a", shader="shaders/masks/spiral.glsl", inputs={ balance="monitor_b", speed="monitor_a", }},
    { dest="monitor_d", shader="shaders/text-surround.glsl", inputs={ speed="monitor_c", text0="monitor_b", img0="monitor_d", }},
    { dest="monitor_c", shader="shaders/boxin.glsl", inputs={ img0="monitor_c", shrink="monitor_b", }},
    { dest="monitor_d", shader="shaders/rgb_to_hsv.glsl", inputs={ rgb="monitor_a", }},
    { dest="monitor_a", shader="shaders/move.glsl", inputs={ offset_x="monitor_b", img0="monitor_c", offset_y="monitor_a", }},
    { dest="monitor_c", shader="shaders/pass.glsl", inputs={ img0="monitor_c", }},
}

pipelines[#pipelines + 1] = {
    { dest="monitor_a", shader="shaders/pass.glsl", inputs={ img0="ObjID:2:assets/animals/free/underwater/Pexels Videos 2558530.mp4-SHRINK-REV.mp4", }},
    { dest="monitor_b", shader="shaders/pass.glsl", inputs={ img0="ObjID:3:assets/animals/free/underwater/Video (1).mp4-SHRINK-REV.mp4", }},
    { dest="monitor_c", shader="shaders/pass.glsl", inputs={ img0="0", }},
    { dest="monitor_d", shader="shaders/pass.glsl", inputs={ img0="0", }},
    { dest="monitor_b", shader="shaders/delay.glsl", inputs={ img0="monitor_d", mix="monitor_a", }},
    { dest="monitor_d", shader="shaders/feedback/blackbar-exploder.glsl", inputs={ last_out="monitor_b", img0="monitor_b", vertical="monitor_c", }},
    { dest="monitor_b", shader="shaders/displace_by_rgb.glsl", inputs={ img0="monitor_d", mix="monitor_a", }},
    { dest="monitor_b", shader="shaders/daily/00005.glsl", inputs={ mix="monitor_c", img0="monitor_c", time="monitor_c", }},
    { dest="monitor_c", shader="shaders/rainbow-band.glsl", inputs={ mix="monitor_a", img0="monitor_a", time="monitor_c", }},
    { dest="monitor_b", shader="shaders/daily/00003.glsl", inputs={ mix="monitor_d", img0="monitor_c", time="monitor_a", }},
    { dest="monitor_c", shader="shaders/fake-3d.glsl", inputs={ scale="monitor_c", img0="monitor_b", depth="monitor_a", }},
    { dest="monitor_c", shader="shaders/hsv_to_rgb.glsl", inputs={ hsv="monitor_b", }},
    { dest="monitor_c", shader="shaders/flip.glsl", inputs={ img0="monitor_c", mix="monitor_b", }},
    { dest="monitor_b", shader="shaders/flip-vertical.glsl", inputs={ img0="monitor_d", mix="monitor_c", }},
    { dest="monitor_a", shader="shaders/explode.glsl", inputs={ img0="monitor_b", mix="monitor_c", }},
    { dest="monitor_c", shader="shaders/text-surround.glsl", inputs={ speed="monitor_b", text0="monitor_a", img0="monitor_c", }},
    { dest="monitor_a", shader="shaders/magnitude.glsl", inputs={ img0="monitor_a", }},
    { dest="monitor_b", shader="shaders/move.glsl", inputs={ offset_x="monitor_c", img0="monitor_d", offset_y="monitor_a", }},
    { dest="monitor_a", shader="shaders/feedback/explode.glsl", inputs={ last_out="monitor_b", }},
    { dest="monitor_a", shader="shaders/negative.glsl", inputs={ img0="monitor_c", mix="monitor_d", }},
    { dest="monitor_b", shader="shaders/color_02.glsl", inputs={ img0="monitor_a", mix="monitor_c", }},
    { dest="monitor_a", shader="shaders/color-tweak.glsl", inputs={ gamma_dec="monitor_a", gamma="monitor_c", split="monitor_b", img0="monitor_d", brightness="monitor_d", contrast_dec="monitor_a", gamma_inc="monitor_b", contrast_inc="monitor_b", contrast="monitor_c", }},
    { dest="monitor_a", shader="shaders/kscope.glsl", inputs={ mix="monitor_d", center="monitor_d", img0="monitor_b", tweak_1="monitor_a", }},
    { dest="monitor_d", shader="shaders/maskify.glsl", inputs={ negate="monitor_a", img0="monitor_b", lumin_threshold="monitor_c", }},
    { dest="monitor_a", shader="shaders/zoom.glsl", inputs={ img0="monitor_a", amount="monitor_b", }},
    { dest="monitor_a", shader="shaders/daily/00002.glsl", inputs={ mix="monitor_c", img0="monitor_c", contrast="monitor_b", }},
    { dest="monitor_b", shader="shaders/mix.glsl", inputs={ mix_diff="monitor_a", mix_fade2="monitor_c", mix_fade3="monitor_a", a="monitor_a", mix_fade="monitor_d", mix_lumin_b="monitor_a", b="monitor_b", mix_lumin_a="monitor_a", mix_bars="monitor_b", }},
    { dest="monitor_a", shader="shaders/invert.glsl", inputs={ mix="monitor_b", img0="monitor_a", }},
    { dest="monitor_d", shader="shaders/knoty.glsl", inputs={ img0="monitor_d", mix="monitor_a", }},
    { dest="monitor_b", shader="shaders/masks/stripes.glsl", inputs={ height="monitor_d", width="monitor_d", }},
    { dest="monitor_c", shader="shaders/rgb_to_hsv.glsl", inputs={ rgb="monitor_b", }},
    { dest="monitor_a", shader="shaders/displace_by_lum.glsl", inputs={ img0="monitor_b", mix="monitor_d", }},
    { dest="monitor_b", shader="shaders/masks/spiral.glsl", inputs={ balance="monitor_c", speed="monitor_d", }},
    { dest="monitor_c", shader="shaders/white-to-black.glsl", inputs={ img0="monitor_c", }},
    { dest="monitor_b", shader="shaders/lums.glsl", inputs={ img0="monitor_c", }},
    { dest="monitor_b", shader="shaders/video-wall.glsl", inputs={ min_brightness="monitor_a", boxes="monitor_b", img0="monitor_c", mix="monitor_d", }},
    { dest="monitor_c", shader="shaders/edges.glsl", inputs={ noise="monitor_d", negate="monitor_b", img0="monitor_d", mix="monitor_b", thresh="monitor_d", }},
    { dest="monitor_d", shader="shaders/mix_fade.glsl", inputs={ b="monitor_d", a="monitor_d", mix="monitor_b", }},
    { dest="monitor_d", shader="shaders/brighter.glsl", inputs={ img0="monitor_d", intensity="monitor_a", }},
    { dest="monitor_d", shader="shaders/band_mix.glsl", inputs={ a="monitor_c", time="monitor_b", bands="monitor_a", b="monitor_a", mix="monitor_c", reference="monitor_b", }},
    { dest="monitor_b", shader="shaders/feedback/implode.glsl", inputs={ last_out="monitor_d", }},
    { dest="monitor_a", shader="shaders/mask.glsl", inputs={ mask="monitor_c", img0="monitor_d", mix="monitor_d", }},
    { dest="monitor_b", shader="shaders/negate.glsl", inputs={ img0="monitor_c", }},
    { dest="monitor_b", shader="shaders/flowing_noise.glsl", inputs={ time="monitor_c", }},
    { dest="monitor_d", shader="shaders/displace_rgb.glsl", inputs={ img0="monitor_c", mix="monitor_c", }},
    { dest="monitor_d", shader="shaders/pass.glsl", inputs={ img0="monitor_d", }},
    { dest="monitor_c", shader="shaders/rotate.glsl", inputs={ img0="monitor_a", speed="monitor_c", }},
    { dest="monitor_a", shader="shaders/boxin.glsl", inputs={ img0="monitor_d", shrink="monitor_c", }},
    { dest="monitor_a", shader="shaders/rgb.glsl", inputs={ red="monitor_b", green="monitor_b", blue="monitor_d", }},
    { dest="monitor_a", shader="shaders/band.glsl", inputs={ target="monitor_d", bands="monitor_b", img0="monitor_a", mix="monitor_c", }},
    { dest="monitor_b", shader="shaders/filter-whites.glsl", inputs={ img0="monitor_a", thresh="monitor_c", }},
    { dest="monitor_c", shader="shaders/test.glsl", inputs={ img0="monitor_d", blue="monitor_d", }},
    { dest="monitor_a", shader="shaders/daily/00006.glsl", inputs={ b="monitor_a", a="monitor_b", mix="monitor_d", }},
    { dest="monitor_b", shader="shaders/blur.glsl", inputs={ img0="monitor_d", mix="monitor_a", }},
    { dest="monitor_b", shader="shaders/color_01.glsl", inputs={ img0="monitor_a", mix="monitor_d", }},
    { dest="monitor_c", shader="shaders/rotate-corners.glsl", inputs={ img0="monitor_b", }},
    { dest="monitor_c", shader="shaders/pixelate.glsl", inputs={ img0="monitor_c", mix="monitor_a", }},
    { dest="monitor_d", shader="shaders/pass.glsl", inputs={ img0="monitor_d", }},
}

pipelines[#pipelines + 1] = {
    { dest="monitor_a", shader="shaders/pass.glsl", inputs={ img0="ObjID:2:assets/animals/free/underwater/Pexels Videos 2558530.mp4-SHRINK-REV.mp4", }},
    { dest="monitor_b", shader="shaders/pass.glsl", inputs={ img0="ObjID:3:assets/animals/free/underwater/Video (1).mp4-SHRINK-REV.mp4", }},
    { dest="monitor_c", shader="shaders/pass.glsl", inputs={ img0="0", }},
    { dest="monitor_d", shader="shaders/pass.glsl", inputs={ img0="0", }},
    { dest="monitor_b", shader="shaders/delay.glsl", inputs={ img0="monitor_d", mix="monitor_a", }},
    { dest="monitor_d", shader="shaders/feedback/blackbar-exploder.glsl", inputs={ last_out="monitor_b", img0="monitor_b", vertical="monitor_c", }},
    { dest="monitor_b", shader="shaders/displace_by_rgb.glsl", inputs={ img0="monitor_d", mix="monitor_a", }},
    { dest="monitor_b", shader="shaders/daily/00005.glsl", inputs={ mix="monitor_c", img0="monitor_c", time="monitor_c", }},
    { dest="monitor_c", shader="shaders/rainbow-band.glsl", inputs={ mix="monitor_a", img0="monitor_a", time="monitor_c", }},
    { dest="monitor_b", shader="shaders/daily/00003.glsl", inputs={ mix="monitor_d", img0="monitor_c", time="monitor_a", }},
    { dest="monitor_c", shader="shaders/fake-3d.glsl", inputs={ scale="monitor_c", img0="monitor_b", depth="monitor_a", }},
    { dest="monitor_c", shader="shaders/hsv_to_rgb.glsl", inputs={ hsv="monitor_b", }},
    { dest="monitor_c", shader="shaders/flip.glsl", inputs={ img0="monitor_c", mix="monitor_b", }},
    { dest="monitor_b", shader="shaders/flip-vertical.glsl", inputs={ img0="monitor_d", mix="monitor_c", }},
    { dest="monitor_a", shader="shaders/explode.glsl", inputs={ img0="monitor_b", mix="monitor_c", }},
    { dest="monitor_c", shader="shaders/text-surround.glsl", inputs={ speed="monitor_b", text0="monitor_a", img0="monitor_c", }},
    { dest="monitor_a", shader="shaders/magnitude.glsl", inputs={ img0="monitor_a", }},
    { dest="monitor_b", shader="shaders/move.glsl", inputs={ offset_x="monitor_c", img0="monitor_d", offset_y="monitor_a", }},
    { dest="monitor_a", shader="shaders/feedback/explode.glsl", inputs={ last_out="monitor_b", }},
    { dest="monitor_a", shader="shaders/negative.glsl", inputs={ img0="monitor_c", mix="monitor_d", }},
    { dest="monitor_b", shader="shaders/color_02.glsl", inputs={ img0="monitor_a", mix="monitor_c", }},
    { dest="monitor_a", shader="shaders/color-tweak.glsl", inputs={ gamma_dec="monitor_a", gamma="monitor_c", split="monitor_b", img0="monitor_d", brightness="monitor_d", contrast_dec="monitor_a", gamma_inc="monitor_b", contrast_inc="monitor_b", contrast="monitor_c", }},
    { dest="monitor_a", shader="shaders/kscope.glsl", inputs={ mix="monitor_d", center="monitor_d", img0="monitor_b", tweak_1="monitor_a", }},
    { dest="monitor_d", shader="shaders/maskify.glsl", inputs={ negate="monitor_a", img0="monitor_b", lumin_threshold="monitor_c", }},
    { dest="monitor_a", shader="shaders/zoom.glsl", inputs={ img0="monitor_a", amount="monitor_b", }},
    { dest="monitor_a", shader="shaders/daily/00002.glsl", inputs={ mix="monitor_c", img0="monitor_c", contrast="monitor_b", }},
    { dest="monitor_b", shader="shaders/mix.glsl", inputs={ mix_diff="monitor_a", mix_fade2="monitor_c", mix_fade3="monitor_a", a="monitor_a", mix_fade="monitor_d", mix_lumin_b="monitor_a", b="monitor_b", mix_lumin_a="monitor_a", mix_bars="monitor_b", }},
    { dest="monitor_a", shader="shaders/invert.glsl", inputs={ mix="monitor_b", img0="monitor_a", }},
    { dest="monitor_d", shader="shaders/knoty.glsl", inputs={ img0="monitor_d", mix="monitor_a", }},
    { dest="monitor_b", shader="shaders/masks/stripes.glsl", inputs={ height="monitor_d", width="monitor_d", }},
    { dest="monitor_c", shader="shaders/rgb_to_hsv.glsl", inputs={ rgb="monitor_b", }},
    { dest="monitor_a", shader="shaders/displace_by_lum.glsl", inputs={ img0="monitor_b", mix="monitor_d", }},
    { dest="monitor_b", shader="shaders/masks/spiral.glsl", inputs={ balance="monitor_c", speed="monitor_d", }},
    { dest="monitor_c", shader="shaders/white-to-black.glsl", inputs={ img0="monitor_c", }},
    { dest="monitor_b", shader="shaders/lums.glsl", inputs={ img0="monitor_c", }},
    { dest="monitor_b", shader="shaders/video-wall.glsl", inputs={ min_brightness="monitor_a", boxes="monitor_b", img0="monitor_c", mix="monitor_d", }},
    { dest="monitor_c", shader="shaders/edges.glsl", inputs={ noise="monitor_d", negate="monitor_b", img0="monitor_d", mix="monitor_b", thresh="monitor_d", }},
    { dest="monitor_d", shader="shaders/mix_fade.glsl", inputs={ b="monitor_d", a="monitor_d", mix="monitor_b", }},
    { dest="monitor_d", shader="shaders/brighter.glsl", inputs={ img0="monitor_d", intensity="monitor_a", }},
    { dest="monitor_d", shader="shaders/band_mix.glsl", inputs={ a="monitor_c", time="monitor_b", bands="monitor_a", b="monitor_a", mix="monitor_c", reference="monitor_b", }},
    { dest="monitor_b", shader="shaders/feedback/implode.glsl", inputs={ last_out="monitor_d", }},
    { dest="monitor_a", shader="shaders/mask.glsl", inputs={ mask="monitor_c", img0="monitor_d", mix="monitor_d", }},
    { dest="monitor_b", shader="shaders/negate.glsl", inputs={ img0="monitor_c", }},
    { dest="monitor_b", shader="shaders/flowing_noise.glsl", inputs={ time="monitor_c", }},
    { dest="monitor_d", shader="shaders/displace_rgb.glsl", inputs={ img0="monitor_c", mix="monitor_c", }},
    { dest="monitor_d", shader="shaders/pass.glsl", inputs={ img0="monitor_d", }},
    { dest="monitor_c", shader="shaders/rotate.glsl", inputs={ img0="monitor_a", speed="monitor_c", }},
    { dest="monitor_a", shader="shaders/boxin.glsl", inputs={ img0="monitor_d", shrink="monitor_c", }},
    { dest="monitor_a", shader="shaders/rgb.glsl", inputs={ red="monitor_b", green="monitor_b", blue="monitor_d", }},
    { dest="monitor_a", shader="shaders/band.glsl", inputs={ target="monitor_d", bands="monitor_b", img0="monitor_a", mix="monitor_c", }},
    { dest="monitor_b", shader="shaders/filter-whites.glsl", inputs={ img0="monitor_a", thresh="monitor_c", }},
    { dest="monitor_c", shader="shaders/test.glsl", inputs={ img0="monitor_d", blue="monitor_d", }},
    { dest="monitor_a", shader="shaders/daily/00006.glsl", inputs={ b="monitor_a", a="monitor_b", mix="monitor_d", }},
    { dest="monitor_b", shader="shaders/blur.glsl", inputs={ img0="monitor_d", mix="monitor_a", }},
    { dest="monitor_b", shader="shaders/color_01.glsl", inputs={ img0="monitor_a", mix="monitor_d", }},
    { dest="monitor_c", shader="shaders/rotate-corners.glsl", inputs={ img0="monitor_b", }},
    { dest="monitor_c", shader="shaders/pixelate.glsl", inputs={ img0="monitor_c", mix="monitor_a", }},
    { dest="monitor_b", shader="shaders/pass.glsl", inputs={ img0="monitor_b", }},
}

pipelines[#pipelines + 1] = {
    { dest="monitor_a", shader="shaders/pass.glsl", inputs={ img0="ObjID:2:assets/animals/free/underwater/Pexels Videos 2558530.mp4-SHRINK-REV.mp4", }},
    { dest="monitor_b", shader="shaders/pass.glsl", inputs={ img0="ObjID:3:assets/animals/free/underwater/Video (1).mp4-SHRINK-REV.mp4", }},
    { dest="monitor_c", shader="shaders/pass.glsl", inputs={ img0="0", }},
    { dest="monitor_d", shader="shaders/pass.glsl", inputs={ img0="0", }},
    { dest="monitor_d", shader="shaders/mix_fade.glsl", inputs={ b="monitor_c", a="monitor_a", mix="monitor_b", }},
    { dest="monitor_a", shader="shaders/edges.glsl", inputs={ noise="monitor_c", negate="monitor_b", img0="monitor_c", mix="monitor_d", thresh="monitor_c", }},
    { dest="monitor_d", shader="shaders/feedback/blackbar-exploder.glsl", inputs={ last_out="monitor_d", img0="monitor_a", vertical="monitor_b", }},
    { dest="monitor_b", shader="shaders/white-to-black.glsl", inputs={ img0="monitor_c", }},
    { dest="monitor_c", shader="shaders/displace_rgb.glsl", inputs={ img0="monitor_c", mix="monitor_c", }},
    { dest="monitor_c", shader="shaders/lums.glsl", inputs={ img0="monitor_b", }},
    { dest="monitor_c", shader="shaders/rgb.glsl", inputs={ red="monitor_b", green="monitor_a", blue="monitor_d", }},
    { dest="monitor_c", shader="shaders/explode.glsl", inputs={ img0="monitor_c", mix="monitor_c", }},
    { dest="monitor_b", shader="shaders/mask.glsl", inputs={ mask="monitor_b", img0="monitor_b", mix="monitor_d", }},
    { dest="monitor_d", shader="shaders/filter-whites.glsl", inputs={ img0="monitor_a", thresh="monitor_d", }},
    { dest="monitor_a", shader="shaders/daily/00005.glsl", inputs={ mix="monitor_a", img0="monitor_b", time="monitor_a", }},
    { dest="monitor_c", shader="shaders/knoty.glsl", inputs={ img0="monitor_d", mix="monitor_b", }},
    { dest="monitor_b", shader="shaders/kscope.glsl", inputs={ mix="monitor_d", center="monitor_c", img0="monitor_c", tweak_1="monitor_a", }},
    { dest="monitor_a", shader="shaders/color_01.glsl", inputs={ img0="monitor_d", mix="monitor_c", }},
    { dest="monitor_a", shader="shaders/feedback/implode.glsl", inputs={ last_out="monitor_c", }},
    { dest="monitor_d", shader="shaders/zoom.glsl", inputs={ img0="monitor_c", amount="monitor_c", }},
    { dest="monitor_b", shader="shaders/negative.glsl", inputs={ img0="monitor_c", mix="monitor_c", }},
    { dest="monitor_c", shader="shaders/boxin.glsl", inputs={ img0="monitor_d", shrink="monitor_a", }},
    { dest="monitor_a", shader="shaders/flowing_noise.glsl", inputs={ time="monitor_b", }},
    { dest="monitor_d", shader="shaders/flip.glsl", inputs={ img0="monitor_d", mix="monitor_a", }},
    { dest="monitor_c", shader="shaders/fake-3d.glsl", inputs={ scale="monitor_d", img0="monitor_d", depth="monitor_d", }},
    { dest="monitor_a", shader="shaders/band.glsl", inputs={ target="monitor_b", bands="monitor_c", img0="monitor_a", mix="monitor_b", }},
    { dest="monitor_b", shader="shaders/flip-vertical.glsl", inputs={ img0="monitor_c", mix="monitor_a", }},
    { dest="monitor_c", shader="shaders/feedback/explode.glsl", inputs={ last_out="monitor_c", }},
    { dest="monitor_c", shader="shaders/daily/00003.glsl", inputs={ mix="monitor_d", img0="monitor_d", time="monitor_a", }},
    { dest="monitor_b", shader="shaders/pixelate.glsl", inputs={ img0="monitor_a", mix="monitor_c", }},
    { dest="monitor_b", shader="shaders/move.glsl", inputs={ offset_x="monitor_a", img0="monitor_a", offset_y="monitor_b", }},
    { dest="monitor_c", shader="shaders/text-surround.glsl", inputs={ speed="monitor_a", text0="monitor_c", img0="monitor_d", }},
    { dest="monitor_a", shader="shaders/rotate.glsl", inputs={ img0="monitor_b", speed="monitor_c", }},
    { dest="monitor_c", shader="shaders/magnitude.glsl", inputs={ img0="monitor_b", }},
    { dest="monitor_b", shader="shaders/daily/00006.glsl", inputs={ b="monitor_c", a="monitor_b", mix="monitor_c", }},
    { dest="monitor_d", shader="shaders/mix.glsl", inputs={ mix_diff="monitor_a", mix_fade2="monitor_b", mix_fade3="monitor_b", a="monitor_d", mix_fade="monitor_a", mix_lumin_b="monitor_b", b="monitor_b", mix_lumin_a="monitor_a", mix_bars="monitor_a", }},
    { dest="monitor_b", shader="shaders/color-tweak.glsl", inputs={ gamma_dec="monitor_d", gamma="monitor_a", split="monitor_b", img0="monitor_d", brightness="monitor_a", contrast_dec="monitor_c", gamma_inc="monitor_c", contrast_inc="monitor_a", contrast="monitor_d", }},
    { dest="monitor_b", shader="shaders/displace_by_rgb.glsl", inputs={ img0="monitor_b", mix="monitor_b", }},
    { dest="monitor_b", shader="shaders/masks/stripes.glsl", inputs={ height="monitor_d", width="monitor_d", }},
    { dest="monitor_b", shader="shaders/maskify.glsl", inputs={ negate="monitor_d", img0="monitor_b", lumin_threshold="monitor_a", }},
    { dest="monitor_a", shader="shaders/video-wall.glsl", inputs={ min_brightness="monitor_d", boxes="monitor_d", img0="monitor_a", mix="monitor_d", }},
    { dest="monitor_b", shader="shaders/pass.glsl", inputs={ img0="monitor_b", }},
    { dest="monitor_b", shader="shaders/masks/spiral.glsl", inputs={ balance="monitor_a", speed="monitor_a", }},
    { dest="monitor_b", shader="shaders/blur.glsl", inputs={ img0="monitor_d", mix="monitor_a", }},
    { dest="monitor_d", shader="shaders/color_02.glsl", inputs={ img0="monitor_a", mix="monitor_a", }},
    { dest="monitor_b", shader="shaders/rainbow-band.glsl", inputs={ mix="monitor_b", img0="monitor_a", time="monitor_c", }},
    { dest="monitor_d", shader="shaders/delay.glsl", inputs={ img0="monitor_b", mix="monitor_b", }},
    { dest="monitor_c", shader="shaders/daily/00002.glsl", inputs={ mix="monitor_d", img0="monitor_a", contrast="monitor_b", }},
    { dest="monitor_d", shader="shaders/test.glsl", inputs={ img0="monitor_d", blue="monitor_a", }},
    { dest="monitor_a", shader="shaders/displace_by_lum.glsl", inputs={ img0="monitor_c", mix="monitor_a", }},
    { dest="monitor_c", shader="shaders/rotate-corners.glsl", inputs={ img0="monitor_b", }},
    { dest="monitor_d", shader="shaders/invert.glsl", inputs={ mix="monitor_d", img0="monitor_b", }},
    { dest="monitor_a", shader="shaders/hsv_to_rgb.glsl", inputs={ hsv="monitor_d", }},
    { dest="monitor_c", shader="shaders/band_mix.glsl", inputs={ a="monitor_d", time="monitor_b", bands="monitor_d", b="monitor_b", mix="monitor_a", reference="monitor_a", }},
    { dest="monitor_a", shader="shaders/rgb_to_hsv.glsl", inputs={ rgb="monitor_b", }},
    { dest="monitor_b", shader="shaders/negate.glsl", inputs={ img0="monitor_d", }},
    { dest="monitor_b", shader="shaders/brighter.glsl", inputs={ img0="monitor_b", intensity="monitor_d", }},
    { dest="monitor_a", shader="shaders/pass.glsl", inputs={ img0="monitor_a", }},
}

